# Site Information
title: SafePath AI
description: Trustworthy AI Solutions for Startups and Non-Profits
url: "" # Replace with your GitHub Pages URL
baseurl: "" # Leave blank for GitHub Pages
author: SafePath AI

# Build Settings
markdown: kramdown
theme: # Leave blank as you're using a custom theme
plugins:
  - jekyll-feed

# Navigation Links
nav:
  - title: "Home"
    url: /
  - title: "About Us"
    url: /about/
  - title: "Services"
    url: /services/
  - title: "Team"
    url: /team/
  - title: "Contact"
    url: /contact/

# SEO Settings
permalink: pretty
paginate: 5

# Social Sharing Information
social:
  twitter: https://twitter.com/safepathai
  linkedin: https://linkedin.com/company/safepathai
  github: https://github.com/<your-username>/SafePath-AI
