title: SafePath AI
description: An Emerging Technologies Clinic for Trustworthy AI Solutions
baseurl: "" # Leave empty for GitHub Pages
url: "https://ebinsaad.github.io/SafePath-AI" # Your GitHub Pages URL
theme: minima # Default Jekyll theme
